const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';
const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

const REQUEST_CATEGORIES="REQUEST_CATEGORIES";
const RECEIVE_CATEGORIES="RECEIVE_CATEGORIES";
const FETCH_CATEGORIES_FAILURE="FETCH_CATEGORIES_FAILURE";

const POST_DOCUMENT="POST_DOCUMENT";
const POST_DOCUMENT_SUCCESS="POST_DOCUMENT_SUCCESS";
const POST_DOCUMENT_FAILURE="POST_DOCUMENT_FAILURE";
const UPDATE_FIELD_DOCUMENT="UPDATE_FIELD_DOCUMENT";
const UPDATE_FILE_DOCUMENT="UPDATE_FILE_DOCUMENT";
const UPDATE_FIELD_DOCUMENT_FOR_ADD="UPDATE_FIELD_DOCUMENT_FOR_ADD";
const UPDATE_FILE_DOCUMENT_FOR_ADD="UPDATE_FILE_DOCUMENT_FOR_ADD";
const DELETE_DOCUMENT_SUCCESS ="DELETE_DOCUMENT_SUCCESS";
const DELETE_DOCUMENT_FAILURE ="DELETE_DOCUMENT_FAILURE";
const REQUEST_DOCUMENTS_CATEGORIES = "REQUEST_DOCUMENTS_CATEGORIES";
const RECEIVE_DOCUMENTS_CATEGORIES = "RECEIVE_DOCUMENTS_CATEGORIES";
const RECEIVE_DETAILS_DOCUMENT_SUCCESS = "RECEIVE_DETAILS__DOCUMENT_SUCCESS";
const RECEIVE_DETAILS_DOCUMENT_FAILURE = "RECEIVE_DETAILS__DOCUMENT_FAILURE";
const REQUEST_DOCUMENT_DETAILS = "REQUEST_DOCUMENT_DETAILS";
const REQUEST_DOCUMENT_TO_UPDATE = "REQUEST_DOCUMENT_TO_UPDATE";
const RECEIVE_DOCUMENT_TO_UPDATE_SUCCESS ="RECEIVE_DOCUMENT_TO_UPDATE_SUCCESS";
const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";
const UPDATE_DOCUMENT_FAILURE = "UPDATE_DOCUMENT_FAILURE";
const VALIDATE_DOCUMENT_FAILURE = "VALIDATE_DOCUMENT_FAILURE";
const UPDATE_DOCUMENT_NAME_FOR_SEARCH = "UPDATE_DOCUMENT_NAME_FOR_SEARCH";
const POST_DOCUMENT_NAME_TO_SEARCH = "POST_DOCUMENT_NAME_TO_SEARCH";
const POST_DOCUMENT_NAME_TO_SEARCH_SUCCESS = "POST_DOCUMENT_NAME_TO_SEARCH_SUCCESS";


export default {
    REQUEST_DOCUMENTS,
    RECEIVE_DOCUMENTS,
    FETCH_DOCUMENTS_FAILURE,
		REQUEST_CATEGORIES,
		RECEIVE_CATEGORIES,
		FETCH_CATEGORIES_FAILURE,
		POST_DOCUMENT,
		POST_DOCUMENT_SUCCESS,
		POST_DOCUMENT_FAILURE,
    UPDATE_FIELD_DOCUMENT,
    UPDATE_FILE_DOCUMENT,
    //Last adds

    DELETE_DOCUMENT_SUCCESS,
    DELETE_DOCUMENT_FAILURE,
    RECEIVE_DOCUMENTS_CATEGORIES,
    REQUEST_DOCUMENTS_CATEGORIES,
    REQUEST_DOCUMENT_DETAILS,
    RECEIVE_DETAILS_DOCUMENT_SUCCESS,
    RECEIVE_DETAILS_DOCUMENT_FAILURE,
    REQUEST_DOCUMENT_TO_UPDATE,
    RECEIVE_DOCUMENT_TO_UPDATE_SUCCESS,
    UPDATE_DOCUMENT,
    UPDATE_DOCUMENT_SUCCESS,
    UPDATE_DOCUMENT_FAILURE,
    VALIDATE_DOCUMENT_FAILURE,
    UPDATE_FILE_DOCUMENT_FOR_ADD,
    UPDATE_FIELD_DOCUMENT_FOR_ADD,
    UPDATE_DOCUMENT_NAME_FOR_SEARCH,
    POST_DOCUMENT_NAME_TO_SEARCH,
    POST_DOCUMENT_NAME_TO_SEARCH_SUCCESS



}